runtime: nodejs9

env_variables:
  NODE_ENV: "production"
  COOKIE_KEY: "vouchersystemcookiekey"
  GOOGLE_CLIENT_ID: "753796190158-7nuhr7phr2pg5qsuh16ubbgosnagbc0g.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET: "I-C5eSzUQ5qRXLF1O4fUBnFd"
  MONGO_URI: "mongodb://voucherprod:password1999@ds027415.mlab.com:27415/voucher-pay"